name: Sync to Private Repo

on:
  push:
    paths:
      - docs/** # Trigger for changes in docs
      - problems/** # Trigger for changes in problems
      - system-design/** # Trigger for changes in system-design
      - design-patterns/** # Trigger for changes in design-patterns

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      - name: Checkout Private Repo
        uses: actions/checkout@v3
        with:
          repository: abhaypaswan/algostreak-nextjs
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private-repo # Directory to clone private repo

      - name: Sync Modified Files for All Folders
        run: |
          # Define source and destination mappings
          declare -A FOLDERS=(
            ["docs"]="apps/www/content/docs"
            ["problems"]="apps/www/content/problems"
            ["system-design"]="apps/www/content/system-design"
            ["design-patterns"]="apps/www/content/design-patterns"
          )

          # Check if HEAD~1 exists
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            BASE_COMMIT="HEAD~1"
          else
            echo "No previous commit found. Syncing all files."
            BASE_COMMIT=""
          fi

          # Loop through all folders and sync changes
          for SRC_FOLDER in "${!FOLDERS[@]}"; do
            DEST_FOLDER="${FOLDERS[$SRC_FOLDER]}"
            
            # If there's no previous commit, consider all files as new
            if [ -z "$BASE_COMMIT" ]; then
              MODIFIED_FILES=$(find "$SRC_FOLDER" -type f)
              DELETED_FILES=""
            else
              MODIFIED_FILES=$(git diff --name-only "$BASE_COMMIT" HEAD -- "$SRC_FOLDER/")
              DELETED_FILES=$(git diff --name-only --diff-filter=D "$BASE_COMMIT" HEAD -- "$SRC_FOLDER/")
            fi

            # Ensure the destination folder exists
            mkdir -p "private-repo/$DEST_FOLDER"

            # Copy modified or new files
            for file in $MODIFIED_FILES; do
              echo "Copying $file to private-repo/$DEST_FOLDER/..."
              mkdir -p "private-repo/$DEST_FOLDER/$(dirname "${file#$SRC_FOLDER/}")"
              cp "$file" "private-repo/$DEST_FOLDER/${file#$SRC_FOLDER/}"
            done

            # Delete files removed in the public repo
            for file in $DELETED_FILES; do
              echo "Deleting $file from private-repo/$DEST_FOLDER/..."
              rm -f "private-repo/$DEST_FOLDER/${file#$SRC_FOLDER/}"
            done
          done

      - name: Push Changes to Private Repo
        run: |
          cd private-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Sync from public repo: $GITHUB_SHA"
          git push
